language: php
php:
  - 7.2
  - 7.1
  - 5.6
  - 5.4
  - 5.3
notifications:
  email: false
before_script:
  - npm prune
script:
  - composer install
  - composer run test
  - sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR_TOKEN -X
# after_script: 'cat ./coverage/lcov.info | coveralls'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
